version: "3"

services:
  es:
    image: 
      elasticsearch:7.12.0
    container_name: 
      my-elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
  app:
    build:
      context: .
    ports: 
      - "5000"
    depends_on:
      - es
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    ports:
      - "80:80"
